# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 11:34
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('funds', models.PositiveIntegerField()),
                ('target', models.CharField(choices=[('A', 'Priority Area A: Future Networks & Communications'), ('B', 'Priority Area B: Data Analytics, Management, Security & Privacy'), ('C', 'Priority Area C: Digital Platforms, Content & Applications'), ('D', 'Priority Area D: Connected Health & Indepentant Living'), ('E', 'Priority Area E: Medical Devices'), ('F', 'Priority Area F: Diagnostics'), ('G', 'Priority Area G: Therapeutics: Synthesis, Formulation, Processing & Drug Delivery'), ('H', 'Priority Area H: Food for Health'), ('I', 'Priority Area I: Sustainable Food Producation & Processing'), ('J', 'Priority Area J: Marine Renewable Energy'), ('K', 'Priority Area K: Smart Grids & Smart Cities'), ('L', 'Priority Area L: Manufacturing Competiveness'), ('M', 'Priority Area M: Processing Technologies & Novel Matierials'), ('N', 'Priority Area N: Innovation in Services & Business Processes'), ('S', 'Software'), ('O', 'Other')], max_length=1, verbose_name='Target audience')),
                ('criteria', models.TextField(verbose_name='Eligibility Criteria')),
                ('template', models.FileField(upload_to='call_templates/%Y/')),
                ('created', models.DateField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100, verbose_name='Duration of the award')),
                ('early_start', models.DateField(verbose_name='Earliest expected start date')),
                ('late_start', models.DateField(verbose_name='Latest expected start date')),
                ('deadline', models.DateField()),
            ],
            options={
                'db_table': 'calls',
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('info', models.TextField(verbose_name='Additional information')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'centers',
            },
        ),
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'funders',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Expected date of completion')),
                ('budget', models.PositiveIntegerField(verbose_name='Project budget')),
                ('title', models.CharField(max_length=100)),
                ('information', models.TextField(verbose_name='Additional information')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Center')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(verbose_name='Details of proposal')),
                ('proposal_document', models.FileField(upload_to=accounts.models.get_proposal_filename)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('r', 'Reviewed'), ('a', 'Accepted'), ('d', 'Denied')], max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proposals',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('job_title', models.CharField(max_length=100)),
                ('prefix', models.CharField(choices=[('mr', 'Mr'), ('rs', 'Mrs'), ('ms', 'Ms'), ('mx', 'Mx'), ('dr', 'Dr'), ('pr', 'Prof')], max_length=2)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone number')),
                ('orcid', models.CharField(blank=True, max_length=19, validators=[django.core.validators.RegexValidator(regex='^(?:(?:\\d){4}-?){4}$')], verbose_name='ORCID number')),
                ('profile_picture', models.ImageField(blank=True, height_field=180, null=True, upload_to='profile_pics', width_field=180)),
            ],
            options={
                'db_table': 'researchers',
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('field', models.CharField(choices=[('A', 'Priority Area A: Future Networks & Communications'), ('B', 'Priority Area B: Data Analytics, Management, Security & Privacy'), ('C', 'Priority Area C: Digital Platforms, Content & Applications'), ('D', 'Priority Area D: Connected Health & Indepentant Living'), ('E', 'Priority Area E: Medical Devices'), ('F', 'Priority Area F: Diagnostics'), ('G', 'Priority Area G: Therapeutics: Synthesis, Formulation, Processing & Drug Delivery'), ('H', 'Priority Area H: Food for Health'), ('I', 'Priority Area I: Sustainable Food Producation & Processing'), ('J', 'Priority Area J: Marine Renewable Energy'), ('K', 'Priority Area K: Smart Grids & Smart Cities'), ('L', 'Priority Area L: Manufacturing Competiveness'), ('M', 'Priority Area M: Processing Technologies & Novel Matierials'), ('N', 'Priority Area N: Innovation in Services & Business Processes'), ('S', 'Software'), ('O', 'Other')], max_length=1)),
            ],
            options={
                'db_table': 'reviewers',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='proposal',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_call', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reviewer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Reviewer'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='researcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='center',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='center',
            name='members',
            field=models.ManyToManyField(db_table='center_researcher', related_name='center_in_center', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Funder'),
        ),
    ]
