# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190219_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='template',
        ),
        migrations.AddField(
            model_name='call',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='call_documents/%Y/'),
        ),
    ]
