# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-24 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_call_criteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='description',
        ),
        migrations.RemoveField(
            model_name='call',
            name='document',
        ),
        migrations.AddField(
            model_name='call',
            name='criteria',
            field=models.TextField(blank=True, null=True, verbose_name='Eligibility Criteria'),
        ),
        migrations.AddField(
            model_name='call',
            name='duration',
            field=models.CharField(default=0, max_length=100, verbose_name='Duration of the award'),
        ),
        migrations.AddField(
            model_name='call',
            name='early_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Earliest expected start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='late_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Latest expected start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='template',
            field=models.FileField(null=True, upload_to='call_templates/%Y/'),
        ),
    ]
