# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190224_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='call',
            name='early_start',
        ),
        migrations.RemoveField(
            model_name='call',
            name='late_start',
        ),
        migrations.AddField(
            model_name='call',
            name='document',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
