# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190225_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='document',
        ),
        migrations.AddField(
            model_name='call',
            name='duration',
            field=models.CharField(default=0, max_length=100, verbose_name='Duration of the award'),
        ),
        migrations.AddField(
            model_name='call',
            name='early_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Earliest expected start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='late_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Latest expected start date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='center',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='prefix',
            field=models.CharField(choices=[('mr', 'Mr.'), ('rs', 'Mrs.'), ('ms', 'Ms.'), ('mx', 'Mx.'), ('dr', 'Dr.'), ('pr', 'Prof.')], max_length=2),
        ),
    ]
