# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190225_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='call',
            name='template',
        ),
        migrations.AddField(
            model_name='call',
            name='file_location',
            field=models.CharField(default='File', max_length=100, verbose_name='File is stored'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_call', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='prefix',
            field=models.CharField(choices=[('mr', 'Mr'), ('rs', 'Mrs'), ('ms', 'Ms'), ('mx', 'Mx'), ('dr', 'Dr'), ('pr', 'Prof')], max_length=2),
        ),
    ]
