# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190226_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='call',
            name='early_start',
        ),
        migrations.RemoveField(
            model_name='call',
            name='late_start',
        ),
    ]
