# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190226_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='description',
            field=models.TextField(default='This is a description', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='call',
            name='target',
            field=models.CharField(choices=[('A', 'Priority Area A: Future Networks & Communications'), ('B', 'Priority Area B: Data Analytics, Management, Security & Privacy'), ('C', 'Priority Area C: Digital Platforms, Content & Applications'), ('D', 'Priority Area D: Connected Health & Indepentant Living'), ('E', 'Priority Area E: Medical Devices'), ('F', 'Priority Area F: Diagnostics'), ('G', 'Priority Area G: Therapeutics: Synthesis, Formulation, Processing & Drug Delivery'), ('H', 'Priority Area H: Food for Health'), ('I', 'Priority Area I: Sustainable Food Producation & Processing'), ('J', 'Priority Area J: Marine Renewable Energy'), ('K', 'Priority Area K: Smart Grids & Smart Cities'), ('L', 'Priority Area L: Manufacturing Competiveness'), ('M', 'Priority Area M: Processing Technologies & Novel Matierials'), ('N', 'Priority Area N: Innovation in Services & Business Processes'), ('S', 'Software'), ('O', 'Other')], max_length=100, verbose_name='Target audience'),
        ),
    ]
