# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-27 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190226_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='details',
        ),
    ]
